In [2]:
pip install --upgrade tensorflow scikit-learn


In [3]:
import tensorflow as tf
from tensorflow.keras import layers, models
from sklearn.datasets import load_wine
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

# Load the Wine dataset
wine = load_wine()
X = wine.data
y = wine.target


In [4]:
X

array([[1.423e+01, 1.710e+00, 2.430e+00, ..., 1.040e+00, 3.920e+00,
        1.065e+03],
       [1.320e+01, 1.780e+00, 2.140e+00, ..., 1.050e+00, 3.400e+00,
        1.050e+03],
       [1.316e+01, 2.360e+00, 2.670e+00, ..., 1.030e+00, 3.170e+00,
        1.185e+03],
       ...,
       [1.327e+01, 4.280e+00, 2.260e+00, ..., 5.900e-01, 1.560e+00,
        8.350e+02],
       [1.317e+01, 2.590e+00, 2.370e+00, ..., 6.000e-01, 1.620e+00,
        8.400e+02],
       [1.413e+01, 4.100e+00, 2.740e+00, ..., 6.100e-01, 1.600e+00,
        5.600e+02]])

In [5]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2])

In [6]:

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Standardize the features
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [7]:
X_train

array([[ 1.66529275, -0.60840587,  1.21896194, ..., -1.65632857,
        -0.87940904, -0.24860607],
       [-0.54952506,  2.7515415 ,  1.00331502, ..., -0.58463272,
        -1.25462095, -0.72992237],
       [-0.74531007, -1.14354109, -0.93750727, ...,  0.35845962,
         0.2462267 , -0.24860607],
       ...,
       [ 1.714239  , -0.44172441,  0.06884503, ...,  1.04434496,
         0.56585166,  2.69572196],
       [-0.35374006, -0.7399965 , -0.36244882, ...,  0.01551695,
        -0.74044166, -0.79631083],
       [-0.78201975,  0.06709269,  0.35637426, ..., -0.67036839,
         1.09392769, -0.98551793]])

In [8]:
# Define a simple neural network model
model = models.Sequential([
    layers.Dense(128, activation='relu', input_shape=(X_train.shape[1],)),
    layers.Dropout(0.5),
    layers.Dense(64, activation='relu'),
    layers.Dense(3, activation='softmax')  # 3 classes for wine dataset
])

# Compile the model
model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])


In [9]:
GPU_on=0

# Check if a GPU is available and print its name
physical_devices = tf.config.list_physical_devices('GPU')
if physical_devices:
    print('GPU found')
    print(f'GPU Name: {physical_devices[0].name}')
    GPU_on=1
else:
    print("No GPU found. Switching to CPU.")
    # Train the model with CPU
    GPU_on=1

print(GPU_on)

No GPU found. Switching to CPU.
1


In [11]:
if GPU_on==1:
    # Train the model with GPU acceleration
    with tf.device('/GPU:0'):
        history = model.fit(X_train, y_train, epochs=10, validation_data=(X_test, y_test))
        print("fiited using GPU")
else:
    # Train the model with CPU
    with tf.device('/CPU:0'):
        history = model.fit(X_train, y_train, epochs=10, validation_data=(X_test, y_test))
        print("fiited using CPU")

Epoch 1/10
5/5 [==============================] - 0s 60ms/step - loss: 0.1584 - accuracy: 0.9718 - val_loss: 0.0969 - val_accuracy: 1.0000
Epoch 2/10
5/5 [==============================] - 0s 29ms/step - loss: 0.1217 - accuracy: 0.9718 - val_loss: 0.0845 - val_accuracy: 1.0000
Epoch 3/10
5/5 [==============================] - 0s 37ms/step - loss: 0.1335 - accuracy: 0.9507 - val_loss: 0.0740 - val_accuracy: 1.0000
Epoch 4/10
5/5 [==============================] - 0s 44ms/step - loss: 0.0989 - accuracy: 0.9648 - val_loss: 0.0643 - val_accuracy: 1.0000
Epoch 5/10
5/5 [==============================] - 0s 33ms/step - loss: 0.1212 - accuracy: 0.9577 - val_loss: 0.0563 - val_accuracy: 1.0000
Epoch 6/10
5/5 [==============================] - 0s 49ms/step - loss: 0.0978 - accuracy: 0.9648 - val_loss: 0.0502 - val_accuracy: 1.0000
Epoch 7/10
5/5 [==============================] - 0s 47ms/step - loss: 0.1164 - accuracy: 0.9507 - val_loss: 0.0447 - val_accuracy: 1.0000
Epoch 8/10
5/5 [===========

In [12]:
# Evaluate the model
test_loss, test_acc = model.evaluate(X_test, y_test)
print(f'Test accuracy: {test_acc}')



2/2 [==============================] - 0s 7ms/step - loss: 0.0320 - accuracy: 1.0000
Test accuracy: 1.0


In [13]:
# Inference with a new record
new_record = scaler.transform([[13.24, 2.59, 2.87, 21.0, 118.0, 2.8, 2.69, 0.39, 1.82, 4.32, 1.04, 2.93, 735.0]])
predictions = model.predict(new_record)
predicted_class = tf.argmax(predictions, axis=1).numpy()[0]
print(predicted_class)

1/1 [==============================] - 0s 139ms/step
0
